name: 'Build and Release'
on:
  pull_request:
  push:
    branches:
      - main
env:
  TAG_NAME: v1.0.0-beta.16

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm run build

      - name: Genarate QrCode index
        uses: iChengbo/generate-qrcode@v0.2.0
        id: getQrcode1
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/index.js

      - name: Genarate QrCode index
        uses: iChengbo/generate-qrcode@v0.2.0
        id: getQrcode2
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/package.json

      - name: Config git
        run: git config --global user.email "name@gmail.com" && git config --global user.name "name"

      - name: Stage & commit changed files
        run: |
          git add .
          git commit -m "update by github actions"

      - name: Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}
          echo ${{ env.TAG_NAME }}
          echo https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/${{ steps.getQRCode1.outputs.QR_CODE_PNG_NAME }}
          echo https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/${{ steps.getQRCode2.outputs.QR_CODE_PNG_NAME }}

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          # artifacts: "index.js,${{ steps.getQRCode.outputs.QR_CODE_PNG_NAME }}"
          body: "![二维码1](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/${{ steps.getQRCode1.outputs.QR_CODE_PNG_NAME }})\n![二维码2](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/${{ steps.getQRCode2.outputs.QR_CODE_PNG_NAME }})"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}

      # - name: Upload release assets
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     body: "![二维码](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/${{ steps.getQRCode.outputs.QR_CODE_PNG_NAME }})"
      #     files: |
      #       index.js
      #       ${{ steps.getQRCode.outputs.QR_CODE_PNG_NAME }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
