name: 'Build2'
on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

# env:
#   TAG_NAME: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm run build2  # 打包2

      - name: Upload Android Products
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: ${{ github.workspace }}/main.js