name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
env:
  TAG_NAME: v1.0.0-beta.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: |
      #     git push origin --delete v1.0.0
      # - run: |
      #     git tag -d v1.0.0 && git push origin :refs/tags/v1.0.0
      # - run: |
      #     npm install
      - run: |
          npm run build
      - name: Genarate QrCode
        uses: iChengbo/generate-qrcode@v0.1.1
        id: getQrcode
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/index.js
      - name: echo path
        run: echo "${{ steps.getQRCode.outputs.QR_CODE_PNG_PATH }}"
      - name: Run a one-line script
        run: echo Hello, github action!
      - name: Config git
        run: git config --global user.email "name@gmail.com" && git config --global user.name "name"
      # - name: Create branch
      #   run: git checkout -b ${{ env.TAG_NAME }}
      - name: Stage changed files
        run: git add .
      - name: Commit changed files
        run: git commit -m "update by github actions"
      - name: Tag
        run: git tag ${{ env.TAG_NAME }}
      - name: Push code
        run: git push origin ${{ env.TAG_NAME }}
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: 
          files: |
            index.js
            qrcode.png


