name: 'Build1'
on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

# env:
#   TAG_NAME: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm run build  # 打包1

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}

      - name: Genarate QrCode index
        uses: iChengbo/generate-qrcode@v0.2.0
        id: getQrcode
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ steps.vars.outputs.tag }}/index.js

      - name: Config git
        run: git config --global user.email "name@gmail.com" && git config --global user.name "name"

      - name: Stage & commit changed files
        run: |
          echo ${{ steps.vars.outputs.tag }}
          git tag -d ${{ steps.vars.outputs.tag }}
          git push origin :refs/tags/${{ steps.vars.outputs.tag }}
          git add .
          git commit -m "update by github actions"

      - name: Tag
        run: |
          git tag ${{ steps.vars.outputs.tag }}
          git push origin ${{ steps.vars.outputs.tag }}

      - name: Upload Android Products
        uses: actions/upload-artifact@v2
        with:
          name: index
          path: ${{ github.workspace }}/index.js

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "index.js" # 不同的文件名
          body: |
            ![二维码1](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ steps.vars.outputs.tag }}/${{ steps.getQRCode.outputs.QR_CODE_PNG_NAME }})
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.tag }}