name: 'Build and Release'
on:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main

jobs:
  build1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm run build  # 打包1

      - name: Save products
        uses: actions/upload-artifact@v2
        with:
          name: index
          path: ${{ github.workspace }}/index.js


  build2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm run build2  # 打包2
          
      - name: Save products
        uses: actions/upload-artifact@v2
        with:
          name: main
          path: ${{ github.workspace }}/main.js


  release:
    needs: [build1, build2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display structure of downloaded files
        run: ls -R

      - name: Download products index
        uses: actions/download-artifact@v2
        with:
          name: index

      - name: Download products main
        uses: actions/download-artifact@v2
        with:
          name: main

      - name: Display structure of downloaded files
        run: ls -R

      - name: Config git
        run: git config --global user.email "name@gmail.com" && git config --global user.name "name"

      - name: Display tag Info
        run: |
          git tag
          echo ${{ github.ref }}

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Genarate QrCode index
        uses: iChengbo/generate-qrcode@v0.2.0
        id: getQrcode1
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ steps.vars.outputs.tag }}/index.js

      - name: Genarate QrCode main
        uses: iChengbo/generate-qrcode@v0.2.0
        id: getQrcode2
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ steps.vars.outputs.tag }}/main.js

      - name: Delete Tag
        run: |
          echo ${{ steps.vars.outputs.tag }}
          git tag -d ${{ steps.vars.outputs.tag }}
          git push origin :refs/tags/${{ steps.vars.outputs.tag }}

      - name: Stage & commit changed files
        run: |
          git add .
          git commit -m "update by github actions"

      - name: Create Tag
        run: |
          git tag ${{ steps.vars.outputs.tag }}
          git push origin ${{ steps.vars.outputs.tag }}

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "index.js, main.js"
          body: |
            ![二维码1](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ steps.vars.outputs.tag }}/${{ steps.getQRCode1.outputs.QR_CODE_PNG_NAME }})
            ![二维码2](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ steps.vars.outputs.tag }}/${{ steps.getQRCode2.outputs.QR_CODE_PNG_NAME }})
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.vars.outputs.tag }}