name: 'Build and Release'
on:
  pull_request:
  push:
    branches:
      - main
env:
  TAG_NAME: v1.0.0-beta.13

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm run build

      - name: Genarate QrCode
        uses: iChengbo/generate-qrcode@v0.1.1
        id: getQrcode
        with:
          text: https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/index.js
      - name: echo path
        run: echo "${{ steps.getQRCode.outputs.QR_CODE_PNG_PATH }}"

      - name: Config git
        run: git config --global user.email "name@gmail.com" && git config --global user.name "name"

      - name: Stage & commit changed files
        run: |
          git add .
          git commit -m "update by github actions"

      - name: Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}
          echo ${{ env.TAG_NAME }}
          echo https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/qrcode.png

      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "index.js,qrcode.png"
          body: "![二维码](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/qrcode.png)"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}

      # - name: Upload release assets
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     body: "![二维码](https://cdn.jsdelivr.net/gh/iChengbo/action-test@${{ env.TAG_NAME }}/qrcode.png)"
      #     files: |
      #       index.js
      #       qrcode.png
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
