name: 'Deploy'
on:
  workflow_run:
    workflows: [ Build1, Build2 ]
    branches: [ main ]
    types: [ completed ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ahmadnassri/action-workflow-run-wait@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2

      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Display tag Info
        run: |
          git tag
          echo ${{ github.ref }}

      - uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: |
          find . -maxdepth 2
