name: 'Release'
on:
  workflow_run:
    workflows: [Build1, Build2]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: index.js

      - uses: actions/download-artifact@v2
        with:
          name: main.js

      - name: Display structure of downloaded files
        run: ls -R